//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating_Reviews
    {
        public int Rating { get; set; }
        public string Review { get; set; }
        public int SchoolID { get; set; }
        public string AddedBy { get; set; }
        public int RatingID { get; set; }
    }
}
