//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int SchoolD { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string Adm_Fee { get; set; }
        public string Fee_PG_Middle { get; set; }
        public string Fee_Matric_OLevel { get; set; }
        public string AddedBy { get; set; }
        public string ImageUrl { get; set; }
    }
}
